site_name: STAAD Grillage Add-in
site_description: Documentation for STAAD Grillage Add-in
site_author: Vivek Patel
site_url: https://nodesautomations.github.io/staad-grillageaddin

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Nodes Automations'

# Configuration
theme:
  name: material
  custom_dir: 'theme'
    # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

   # Default values, taken from mkdocs_theme.yml
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  logo: 
    icon: 'home'
  font:
    text: Roboto
    code: Roboto Mono

  
# Customization
extra:
  social:
    - type: globe
      link: https://www.nodesautomations.com
    - type: youtube
      link: https://www.youtube.com/channel/UCnrjW31os9P6_MtSZXt6o-g
    - type: linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/
    - type: envelope
      link: mailto:vivek@nodesautomations.com

# Extensions
markdown_extensions:
  - attr_list # For Image Resize
  - markdown.extensions.admonition # For Block Style
  - markdown.extensions.codehilite: # code syntax Highlighting
      guess_lang: false
      linenums: true
  - pymdownx.caret # super Script
  - pymdownx.critic # enables the tracking of changes (additions, deletions and comments) on documents
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.mark #Mark adds the ability to insert <mark></mark> tags for highlighting
  - pymdownx.magiclink # auto-linking HTTP, FTP and email links.
  - pymdownx.tasklist # adds GFM style task lists.
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.css
  
extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

nav:
    - Home: index.md
    - Getting Started : getting-started.md
    - Ribbon : ribbon/ribbon.md
    - Geometry :
      - Basic : geometry/basic.md
      - Skew : geometry/skew.md
      - Tapered : geometry/tapered.md
      - Curvature : geometry/curvature.md
      - Extra Nodes : geometry/extra-nodes.md
    - Properties : properties/properties.md
    - Loads :
      - Dead Loads : loads/dead-loads.md
      - Live Loads : loads/live-loads.md
      - Load Combination : loads/load-combinations.md
    - FAQ : faq.md
    - Links : links.md

use_directory_urls: false